<?php
/**
 * ContaApi
 * PHP version 7.4
 *
 * @category Class
 * @package  ACBrAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ACBr API
 *
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ACBrAPI\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use ACBrAPI\ApiException;
use ACBrAPI\Configuration;
use ACBrAPI\HeaderSelector;
use ACBrAPI\ObjectSerializer;

/**
 * ContaApi Class Doc Comment
 *
 * @category Class
 * @package  ACBrAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContaApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'consultarCotaConta' => [
            'application/json',
        ],
        'consultarCotaPrePago' => [
            'application/json',
        ],
        'listarCotasConta' => [
            'application/json',
        ],
        'listarExtratoCreditosConta' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation consultarCotaConta
     *
     * Consultar o limite de uso e o consumo de uma cota específica.
     *
     * @param  string $nome Nome da cota a ser consultada. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['consultarCotaConta'] to see the possible values for this operation
     *
     * @throws \ACBrAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ACBrAPI\Model\ContaCota
     */
    public function consultarCotaConta($nome, string $contentType = self::contentTypes['consultarCotaConta'][0])
    {
        list($response) = $this->consultarCotaContaWithHttpInfo($nome, $contentType);
        return $response;
    }

    /**
     * Operation consultarCotaContaWithHttpInfo
     *
     * Consultar o limite de uso e o consumo de uma cota específica.
     *
     * @param  string $nome Nome da cota a ser consultada. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['consultarCotaConta'] to see the possible values for this operation
     *
     * @throws \ACBrAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ACBrAPI\Model\ContaCota, HTTP status code, HTTP response headers (array of strings)
     */
    public function consultarCotaContaWithHttpInfo($nome, string $contentType = self::contentTypes['consultarCotaConta'][0])
    {
        $request = $this->consultarCotaContaRequest($nome, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\ACBrAPI\Model\ContaCota' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ACBrAPI\Model\ContaCota' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ACBrAPI\Model\ContaCota', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ACBrAPI\Model\ContaCota';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ACBrAPI\Model\ContaCota',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation consultarCotaContaAsync
     *
     * Consultar o limite de uso e o consumo de uma cota específica.
     *
     * @param  string $nome Nome da cota a ser consultada. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['consultarCotaConta'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function consultarCotaContaAsync($nome, string $contentType = self::contentTypes['consultarCotaConta'][0])
    {
        return $this->consultarCotaContaAsyncWithHttpInfo($nome, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation consultarCotaContaAsyncWithHttpInfo
     *
     * Consultar o limite de uso e o consumo de uma cota específica.
     *
     * @param  string $nome Nome da cota a ser consultada. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['consultarCotaConta'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function consultarCotaContaAsyncWithHttpInfo($nome, string $contentType = self::contentTypes['consultarCotaConta'][0])
    {
        $returnType = '\ACBrAPI\Model\ContaCota';
        $request = $this->consultarCotaContaRequest($nome, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'consultarCotaConta'
     *
     * @param  string $nome Nome da cota a ser consultada. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['consultarCotaConta'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function consultarCotaContaRequest($nome, string $contentType = self::contentTypes['consultarCotaConta'][0])
    {

        // verify the required parameter 'nome' is set
        if ($nome === null || (is_array($nome) && count($nome) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $nome when calling consultarCotaConta'
            );
        }


        $resourcePath = '/conta/cotas/{nome}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($nome !== null) {
            $resourcePath = str_replace(
                '{' . 'nome' . '}',
                ObjectSerializer::toPathValue($nome),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation consultarCotaPrePago
     *
     * Consultar o resumo da cota de créditos pré-pagos.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['consultarCotaPrePago'] to see the possible values for this operation
     *
     * @throws \ACBrAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ACBrAPI\Model\ContaCotaPrePago
     */
    public function consultarCotaPrePago(string $contentType = self::contentTypes['consultarCotaPrePago'][0])
    {
        list($response) = $this->consultarCotaPrePagoWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation consultarCotaPrePagoWithHttpInfo
     *
     * Consultar o resumo da cota de créditos pré-pagos.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['consultarCotaPrePago'] to see the possible values for this operation
     *
     * @throws \ACBrAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ACBrAPI\Model\ContaCotaPrePago, HTTP status code, HTTP response headers (array of strings)
     */
    public function consultarCotaPrePagoWithHttpInfo(string $contentType = self::contentTypes['consultarCotaPrePago'][0])
    {
        $request = $this->consultarCotaPrePagoRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\ACBrAPI\Model\ContaCotaPrePago' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ACBrAPI\Model\ContaCotaPrePago' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ACBrAPI\Model\ContaCotaPrePago', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ACBrAPI\Model\ContaCotaPrePago';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ACBrAPI\Model\ContaCotaPrePago',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation consultarCotaPrePagoAsync
     *
     * Consultar o resumo da cota de créditos pré-pagos.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['consultarCotaPrePago'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function consultarCotaPrePagoAsync(string $contentType = self::contentTypes['consultarCotaPrePago'][0])
    {
        return $this->consultarCotaPrePagoAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation consultarCotaPrePagoAsyncWithHttpInfo
     *
     * Consultar o resumo da cota de créditos pré-pagos.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['consultarCotaPrePago'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function consultarCotaPrePagoAsyncWithHttpInfo(string $contentType = self::contentTypes['consultarCotaPrePago'][0])
    {
        $returnType = '\ACBrAPI\Model\ContaCotaPrePago';
        $request = $this->consultarCotaPrePagoRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'consultarCotaPrePago'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['consultarCotaPrePago'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function consultarCotaPrePagoRequest(string $contentType = self::contentTypes['consultarCotaPrePago'][0])
    {


        $resourcePath = '/conta/cotas/prepago';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listarCotasConta
     *
     * Consultar os limites de uso e consumo das cotas disponíveis, exceto a cota de créditos pré-pagos.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listarCotasConta'] to see the possible values for this operation
     *
     * @throws \ACBrAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ACBrAPI\Model\ContaCotaListagem
     * @deprecated
     */
    public function listarCotasConta(string $contentType = self::contentTypes['listarCotasConta'][0])
    {
        list($response) = $this->listarCotasContaWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation listarCotasContaWithHttpInfo
     *
     * Consultar os limites de uso e consumo das cotas disponíveis, exceto a cota de créditos pré-pagos.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listarCotasConta'] to see the possible values for this operation
     *
     * @throws \ACBrAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ACBrAPI\Model\ContaCotaListagem, HTTP status code, HTTP response headers (array of strings)
     * @deprecated
     */
    public function listarCotasContaWithHttpInfo(string $contentType = self::contentTypes['listarCotasConta'][0])
    {
        $request = $this->listarCotasContaRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\ACBrAPI\Model\ContaCotaListagem' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ACBrAPI\Model\ContaCotaListagem' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ACBrAPI\Model\ContaCotaListagem', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ACBrAPI\Model\ContaCotaListagem';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ACBrAPI\Model\ContaCotaListagem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listarCotasContaAsync
     *
     * Consultar os limites de uso e consumo das cotas disponíveis, exceto a cota de créditos pré-pagos.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listarCotasConta'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function listarCotasContaAsync(string $contentType = self::contentTypes['listarCotasConta'][0])
    {
        return $this->listarCotasContaAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listarCotasContaAsyncWithHttpInfo
     *
     * Consultar os limites de uso e consumo das cotas disponíveis, exceto a cota de créditos pré-pagos.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listarCotasConta'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function listarCotasContaAsyncWithHttpInfo(string $contentType = self::contentTypes['listarCotasConta'][0])
    {
        $returnType = '\ACBrAPI\Model\ContaCotaListagem';
        $request = $this->listarCotasContaRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listarCotasConta'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listarCotasConta'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     * @deprecated
     */
    public function listarCotasContaRequest(string $contentType = self::contentTypes['listarCotasConta'][0])
    {


        $resourcePath = '/conta/cotas';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listarExtratoCreditosConta
     *
     * Consultar o extrato de movimentação de créditos do tenant atual.
     *
     * @param  string $data_inicial data_inicial (optional)
     * @param  string $data_final data_final (optional)
     * @param  int $top top (optional)
     * @param  int $skip skip (optional)
     * @param  int $limit limit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listarExtratoCreditosConta'] to see the possible values for this operation
     *
     * @throws \ACBrAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ACBrAPI\Model\ContaExtratoCreditoListagem
     */
    public function listarExtratoCreditosConta($data_inicial = null, $data_final = null, $top = null, $skip = null, $limit = null, string $contentType = self::contentTypes['listarExtratoCreditosConta'][0])
    {
        list($response) = $this->listarExtratoCreditosContaWithHttpInfo($data_inicial, $data_final, $top, $skip, $limit, $contentType);
        return $response;
    }

    /**
     * Operation listarExtratoCreditosContaWithHttpInfo
     *
     * Consultar o extrato de movimentação de créditos do tenant atual.
     *
     * @param  string $data_inicial (optional)
     * @param  string $data_final (optional)
     * @param  int $top (optional)
     * @param  int $skip (optional)
     * @param  int $limit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listarExtratoCreditosConta'] to see the possible values for this operation
     *
     * @throws \ACBrAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ACBrAPI\Model\ContaExtratoCreditoListagem, HTTP status code, HTTP response headers (array of strings)
     */
    public function listarExtratoCreditosContaWithHttpInfo($data_inicial = null, $data_final = null, $top = null, $skip = null, $limit = null, string $contentType = self::contentTypes['listarExtratoCreditosConta'][0])
    {
        $request = $this->listarExtratoCreditosContaRequest($data_inicial, $data_final, $top, $skip, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\ACBrAPI\Model\ContaExtratoCreditoListagem' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ACBrAPI\Model\ContaExtratoCreditoListagem' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ACBrAPI\Model\ContaExtratoCreditoListagem', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ACBrAPI\Model\ContaExtratoCreditoListagem';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ACBrAPI\Model\ContaExtratoCreditoListagem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listarExtratoCreditosContaAsync
     *
     * Consultar o extrato de movimentação de créditos do tenant atual.
     *
     * @param  string $data_inicial (optional)
     * @param  string $data_final (optional)
     * @param  int $top (optional)
     * @param  int $skip (optional)
     * @param  int $limit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listarExtratoCreditosConta'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listarExtratoCreditosContaAsync($data_inicial = null, $data_final = null, $top = null, $skip = null, $limit = null, string $contentType = self::contentTypes['listarExtratoCreditosConta'][0])
    {
        return $this->listarExtratoCreditosContaAsyncWithHttpInfo($data_inicial, $data_final, $top, $skip, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listarExtratoCreditosContaAsyncWithHttpInfo
     *
     * Consultar o extrato de movimentação de créditos do tenant atual.
     *
     * @param  string $data_inicial (optional)
     * @param  string $data_final (optional)
     * @param  int $top (optional)
     * @param  int $skip (optional)
     * @param  int $limit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listarExtratoCreditosConta'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listarExtratoCreditosContaAsyncWithHttpInfo($data_inicial = null, $data_final = null, $top = null, $skip = null, $limit = null, string $contentType = self::contentTypes['listarExtratoCreditosConta'][0])
    {
        $returnType = '\ACBrAPI\Model\ContaExtratoCreditoListagem';
        $request = $this->listarExtratoCreditosContaRequest($data_inicial, $data_final, $top, $skip, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listarExtratoCreditosConta'
     *
     * @param  string $data_inicial (optional)
     * @param  string $data_final (optional)
     * @param  int $top (optional)
     * @param  int $skip (optional)
     * @param  int $limit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listarExtratoCreditosConta'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listarExtratoCreditosContaRequest($data_inicial = null, $data_final = null, $top = null, $skip = null, $limit = null, string $contentType = self::contentTypes['listarExtratoCreditosConta'][0])
    {







        $resourcePath = '/conta/extrato';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $data_inicial,
            'data_inicial', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $data_final,
            'data_final', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $top,
            'top', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skip,
            'skip', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
