<?php
/**
 * CteOsSefazPagamentoRTCOS
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ACBrAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ACBr API
 *
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ACBrAPI\Model;

use \ArrayAccess;
use \ACBrAPI\ObjectSerializer;

/**
 * CteOsSefazPagamentoRTCOS Class Doc Comment
 *
 * @category Class
 * @description Dados de cada pagamento previsto.
 * @package  ACBrAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CteOsSefazPagamentoRTCOS implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CteOsSefazPagamentoRTCOS';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'n_pag' => 'string',
        'id_transacao' => 'string',
        'tp_meio_pgto' => 'string',
        'cnpj_receb' => 'string',
        'cnpj_base_psp' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'n_pag' => null,
        'id_transacao' => null,
        'tp_meio_pgto' => null,
        'cnpj_receb' => null,
        'cnpj_base_psp' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'n_pag' => true,
		'id_transacao' => true,
		'tp_meio_pgto' => true,
		'cnpj_receb' => true,
		'cnpj_base_psp' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'n_pag' => 'nPag',
        'id_transacao' => 'idTransacao',
        'tp_meio_pgto' => 'tpMeioPgto',
        'cnpj_receb' => 'CNPJReceb',
        'cnpj_base_psp' => 'CNPJBasePSP'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'n_pag' => 'setNPag',
        'id_transacao' => 'setIdTransacao',
        'tp_meio_pgto' => 'setTpMeioPgto',
        'cnpj_receb' => 'setCnpjReceb',
        'cnpj_base_psp' => 'setCnpjBasePsp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'n_pag' => 'getNPag',
        'id_transacao' => 'getIdTransacao',
        'tp_meio_pgto' => 'getTpMeioPgto',
        'cnpj_receb' => 'getCnpjReceb',
        'cnpj_base_psp' => 'getCnpjBasePsp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('n_pag', $data ?? [], null);
        $this->setIfExists('id_transacao', $data ?? [], null);
        $this->setIfExists('tp_meio_pgto', $data ?? [], null);
        $this->setIfExists('cnpj_receb', $data ?? [], null);
        $this->setIfExists('cnpj_base_psp', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['n_pag'] === null) {
            $invalidProperties[] = "'n_pag' can't be null";
        }
        if ($this->container['id_transacao'] === null) {
            $invalidProperties[] = "'id_transacao' can't be null";
        }
        if ((mb_strlen($this->container['id_transacao']) > 35)) {
            $invalidProperties[] = "invalid value for 'id_transacao', the character length must be smaller than or equal to 35.";
        }

        if ((mb_strlen($this->container['id_transacao']) < 2)) {
            $invalidProperties[] = "invalid value for 'id_transacao', the character length must be bigger than or equal to 2.";
        }

        if ($this->container['tp_meio_pgto'] === null) {
            $invalidProperties[] = "'tp_meio_pgto' can't be null";
        }
        if ($this->container['cnpj_receb'] === null) {
            $invalidProperties[] = "'cnpj_receb' can't be null";
        }
        if ($this->container['cnpj_base_psp'] === null) {
            $invalidProperties[] = "'cnpj_base_psp' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets n_pag
     *
     * @return string
     */
    public function getNPag()
    {
        return $this->container['n_pag'];
    }

    /**
     * Sets n_pag
     *
     * @param string $n_pag Número sequencial do pagamento.
     *
     * @return self
     */
    public function setNPag($n_pag)
    {
        if (is_null($n_pag)) {
            array_push($this->openAPINullablesSetToNull, 'n_pag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('n_pag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['n_pag'] = $n_pag;

        return $this;
    }

    /**
     * Gets id_transacao
     *
     * @return string
     */
    public function getIdTransacao()
    {
        return $this->container['id_transacao'];
    }

    /**
     * Sets id_transacao
     *
     * @param string $id_transacao ID específico da transação financeira conforme o meio de pagamento.
     *
     * @return self
     */
    public function setIdTransacao($id_transacao)
    {
        if (is_null($id_transacao)) {
            array_push($this->openAPINullablesSetToNull, 'id_transacao');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id_transacao', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($id_transacao) && (mb_strlen($id_transacao) > 35)) {
            throw new \InvalidArgumentException('invalid length for $id_transacao when calling CteOsSefazPagamentoRTCOS., must be smaller than or equal to 35.');
        }
        if (!is_null($id_transacao) && (mb_strlen($id_transacao) < 2)) {
            throw new \InvalidArgumentException('invalid length for $id_transacao when calling CteOsSefazPagamentoRTCOS., must be bigger than or equal to 2.');
        }

        $this->container['id_transacao'] = $id_transacao;

        return $this;
    }

    /**
     * Gets tp_meio_pgto
     *
     * @return string
     */
    public function getTpMeioPgto()
    {
        return $this->container['tp_meio_pgto'];
    }

    /**
     * Sets tp_meio_pgto
     *
     * @param string $tp_meio_pgto (Meio de pagamento utilizado (ver IT DFe 2026.001).
     *
     * @return self
     */
    public function setTpMeioPgto($tp_meio_pgto)
    {
        if (is_null($tp_meio_pgto)) {
            array_push($this->openAPINullablesSetToNull, 'tp_meio_pgto');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tp_meio_pgto', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tp_meio_pgto'] = $tp_meio_pgto;

        return $this;
    }

    /**
     * Gets cnpj_receb
     *
     * @return string
     */
    public function getCnpjReceb()
    {
        return $this->container['cnpj_receb'];
    }

    /**
     * Sets cnpj_receb
     *
     * @param string $cnpj_receb CNPJ do recebedor do pagamento.  Informar zeros não significativos.
     *
     * @return self
     */
    public function setCnpjReceb($cnpj_receb)
    {
        if (is_null($cnpj_receb)) {
            array_push($this->openAPINullablesSetToNull, 'cnpj_receb');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cnpj_receb', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cnpj_receb'] = $cnpj_receb;

        return $this;
    }

    /**
     * Gets cnpj_base_psp
     *
     * @return string
     */
    public function getCnpjBasePsp()
    {
        return $this->container['cnpj_base_psp'];
    }

    /**
     * Sets cnpj_base_psp
     *
     * @param string $cnpj_base_psp CNPJ base da instituição financeira.  Informar zeros não significativos.
     *
     * @return self
     */
    public function setCnpjBasePsp($cnpj_base_psp)
    {
        if (is_null($cnpj_base_psp)) {
            array_push($this->openAPINullablesSetToNull, 'cnpj_base_psp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cnpj_base_psp', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cnpj_base_psp'] = $cnpj_base_psp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


