<?php
/**
 * CteSefazInfCte
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ACBrAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Nuvem Fiscal
 *
 * API para automação comercial e documentos fiscais.
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ACBrAPI\Model;

use \ArrayAccess;
use \ACBrAPI\ObjectSerializer;

/**
 * CteSefazInfCte Class Doc Comment
 *
 * @category Class
 * @description Informações do CT-e.
 * @package  ACBrAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CteSefazInfCte implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CteSefazInfCte';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'versao' => 'string',
        'id' => 'string',
        'ide' => '\ACBrAPI\Model\CteSefazIde',
        'compl' => '\ACBrAPI\Model\CteSefazCompl',
        'emit' => '\ACBrAPI\Model\CteSefazEmit',
        'rem' => '\ACBrAPI\Model\CteSefazRem',
        'exped' => '\ACBrAPI\Model\CteSefazExped',
        'receb' => '\ACBrAPI\Model\CteSefazReceb',
        'dest' => '\ACBrAPI\Model\CteSefazDest',
        'v_prest' => '\ACBrAPI\Model\CteSefazVPrest',
        'imp' => '\ACBrAPI\Model\CteSefazInfCteImp',
        'inf_cte_norm' => '\ACBrAPI\Model\CteSefazInfCTeNorm',
        'inf_cte_comp' => '\ACBrAPI\Model\CteSefazInfCteComp[]',
        'aut_xml' => '\ACBrAPI\Model\CteSefazAutXML[]',
        'inf_resp_tec' => '\ACBrAPI\Model\CteSefazRespTec',
        'inf_solic_nff' => '\ACBrAPI\Model\CteSefazInfSolicNFF'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'versao' => null,
        'id' => null,
        'ide' => null,
        'compl' => null,
        'emit' => null,
        'rem' => null,
        'exped' => null,
        'receb' => null,
        'dest' => null,
        'v_prest' => null,
        'imp' => null,
        'inf_cte_norm' => null,
        'inf_cte_comp' => null,
        'aut_xml' => null,
        'inf_resp_tec' => null,
        'inf_solic_nff' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'versao' => true,
        'id' => true,
        'ide' => false,
        'compl' => false,
        'emit' => false,
        'rem' => false,
        'exped' => false,
        'receb' => false,
        'dest' => false,
        'v_prest' => false,
        'imp' => false,
        'inf_cte_norm' => false,
        'inf_cte_comp' => false,
        'aut_xml' => false,
        'inf_resp_tec' => false,
        'inf_solic_nff' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'versao' => 'versao',
        'id' => 'Id',
        'ide' => 'ide',
        'compl' => 'compl',
        'emit' => 'emit',
        'rem' => 'rem',
        'exped' => 'exped',
        'receb' => 'receb',
        'dest' => 'dest',
        'v_prest' => 'vPrest',
        'imp' => 'imp',
        'inf_cte_norm' => 'infCTeNorm',
        'inf_cte_comp' => 'infCteComp',
        'aut_xml' => 'autXML',
        'inf_resp_tec' => 'infRespTec',
        'inf_solic_nff' => 'infSolicNFF'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'versao' => 'setVersao',
        'id' => 'setId',
        'ide' => 'setIde',
        'compl' => 'setCompl',
        'emit' => 'setEmit',
        'rem' => 'setRem',
        'exped' => 'setExped',
        'receb' => 'setReceb',
        'dest' => 'setDest',
        'v_prest' => 'setVPrest',
        'imp' => 'setImp',
        'inf_cte_norm' => 'setInfCteNorm',
        'inf_cte_comp' => 'setInfCteComp',
        'aut_xml' => 'setAutXml',
        'inf_resp_tec' => 'setInfRespTec',
        'inf_solic_nff' => 'setInfSolicNff'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'versao' => 'getVersao',
        'id' => 'getId',
        'ide' => 'getIde',
        'compl' => 'getCompl',
        'emit' => 'getEmit',
        'rem' => 'getRem',
        'exped' => 'getExped',
        'receb' => 'getReceb',
        'dest' => 'getDest',
        'v_prest' => 'getVPrest',
        'imp' => 'getImp',
        'inf_cte_norm' => 'getInfCteNorm',
        'inf_cte_comp' => 'getInfCteComp',
        'aut_xml' => 'getAutXml',
        'inf_resp_tec' => 'getInfRespTec',
        'inf_solic_nff' => 'getInfSolicNff'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('versao', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('ide', $data ?? [], null);
        $this->setIfExists('compl', $data ?? [], null);
        $this->setIfExists('emit', $data ?? [], null);
        $this->setIfExists('rem', $data ?? [], null);
        $this->setIfExists('exped', $data ?? [], null);
        $this->setIfExists('receb', $data ?? [], null);
        $this->setIfExists('dest', $data ?? [], null);
        $this->setIfExists('v_prest', $data ?? [], null);
        $this->setIfExists('imp', $data ?? [], null);
        $this->setIfExists('inf_cte_norm', $data ?? [], null);
        $this->setIfExists('inf_cte_comp', $data ?? [], null);
        $this->setIfExists('aut_xml', $data ?? [], null);
        $this->setIfExists('inf_resp_tec', $data ?? [], null);
        $this->setIfExists('inf_solic_nff', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['versao'] === null) {
            $invalidProperties[] = "'versao' can't be null";
        }
        if ($this->container['ide'] === null) {
            $invalidProperties[] = "'ide' can't be null";
        }
        if ($this->container['emit'] === null) {
            $invalidProperties[] = "'emit' can't be null";
        }
        if ($this->container['v_prest'] === null) {
            $invalidProperties[] = "'v_prest' can't be null";
        }
        if ($this->container['imp'] === null) {
            $invalidProperties[] = "'imp' can't be null";
        }
        if (!is_null($this->container['inf_cte_comp']) && (count($this->container['inf_cte_comp']) > 10)) {
            $invalidProperties[] = "invalid value for 'inf_cte_comp', number of items must be less than or equal to 10.";
        }

        if (!is_null($this->container['aut_xml']) && (count($this->container['aut_xml']) > 10)) {
            $invalidProperties[] = "invalid value for 'aut_xml', number of items must be less than or equal to 10.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets versao
     *
     * @return string
     */
    public function getVersao()
    {
        return $this->container['versao'];
    }

    /**
     * Sets versao
     *
     * @param string $versao Versão do leiaute.  Ex: \"4.00\".
     *
     * @return self
     */
    public function setVersao($versao)
    {
        if (is_null($versao)) {
            array_push($this->openAPINullablesSetToNull, 'versao');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('versao', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['versao'] = $versao;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Identificador da tag a ser assinada.  Informar a chave de acesso do CT-e e precedida do literal \"CTe\".    *Geramos automaticamente quando nenhum valor é informado.*
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets ide
     *
     * @return \ACBrAPI\Model\CteSefazIde
     */
    public function getIde()
    {
        return $this->container['ide'];
    }

    /**
     * Sets ide
     *
     * @param \ACBrAPI\Model\CteSefazIde $ide ide
     *
     * @return self
     */
    public function setIde($ide)
    {
        if (is_null($ide)) {
            throw new \InvalidArgumentException('non-nullable ide cannot be null');
        }
        $this->container['ide'] = $ide;

        return $this;
    }

    /**
     * Gets compl
     *
     * @return \ACBrAPI\Model\CteSefazCompl|null
     */
    public function getCompl()
    {
        return $this->container['compl'];
    }

    /**
     * Sets compl
     *
     * @param \ACBrAPI\Model\CteSefazCompl|null $compl compl
     *
     * @return self
     */
    public function setCompl($compl)
    {
        if (is_null($compl)) {
            throw new \InvalidArgumentException('non-nullable compl cannot be null');
        }
        $this->container['compl'] = $compl;

        return $this;
    }

    /**
     * Gets emit
     *
     * @return \ACBrAPI\Model\CteSefazEmit
     */
    public function getEmit()
    {
        return $this->container['emit'];
    }

    /**
     * Sets emit
     *
     * @param \ACBrAPI\Model\CteSefazEmit $emit emit
     *
     * @return self
     */
    public function setEmit($emit)
    {
        if (is_null($emit)) {
            throw new \InvalidArgumentException('non-nullable emit cannot be null');
        }
        $this->container['emit'] = $emit;

        return $this;
    }

    /**
     * Gets rem
     *
     * @return \ACBrAPI\Model\CteSefazRem|null
     */
    public function getRem()
    {
        return $this->container['rem'];
    }

    /**
     * Sets rem
     *
     * @param \ACBrAPI\Model\CteSefazRem|null $rem rem
     *
     * @return self
     */
    public function setRem($rem)
    {
        if (is_null($rem)) {
            throw new \InvalidArgumentException('non-nullable rem cannot be null');
        }
        $this->container['rem'] = $rem;

        return $this;
    }

    /**
     * Gets exped
     *
     * @return \ACBrAPI\Model\CteSefazExped|null
     */
    public function getExped()
    {
        return $this->container['exped'];
    }

    /**
     * Sets exped
     *
     * @param \ACBrAPI\Model\CteSefazExped|null $exped exped
     *
     * @return self
     */
    public function setExped($exped)
    {
        if (is_null($exped)) {
            throw new \InvalidArgumentException('non-nullable exped cannot be null');
        }
        $this->container['exped'] = $exped;

        return $this;
    }

    /**
     * Gets receb
     *
     * @return \ACBrAPI\Model\CteSefazReceb|null
     */
    public function getReceb()
    {
        return $this->container['receb'];
    }

    /**
     * Sets receb
     *
     * @param \ACBrAPI\Model\CteSefazReceb|null $receb receb
     *
     * @return self
     */
    public function setReceb($receb)
    {
        if (is_null($receb)) {
            throw new \InvalidArgumentException('non-nullable receb cannot be null');
        }
        $this->container['receb'] = $receb;

        return $this;
    }

    /**
     * Gets dest
     *
     * @return \ACBrAPI\Model\CteSefazDest|null
     */
    public function getDest()
    {
        return $this->container['dest'];
    }

    /**
     * Sets dest
     *
     * @param \ACBrAPI\Model\CteSefazDest|null $dest dest
     *
     * @return self
     */
    public function setDest($dest)
    {
        if (is_null($dest)) {
            throw new \InvalidArgumentException('non-nullable dest cannot be null');
        }
        $this->container['dest'] = $dest;

        return $this;
    }

    /**
     * Gets v_prest
     *
     * @return \ACBrAPI\Model\CteSefazVPrest
     */
    public function getVPrest()
    {
        return $this->container['v_prest'];
    }

    /**
     * Sets v_prest
     *
     * @param \ACBrAPI\Model\CteSefazVPrest $v_prest v_prest
     *
     * @return self
     */
    public function setVPrest($v_prest)
    {
        if (is_null($v_prest)) {
            throw new \InvalidArgumentException('non-nullable v_prest cannot be null');
        }
        $this->container['v_prest'] = $v_prest;

        return $this;
    }

    /**
     * Gets imp
     *
     * @return \ACBrAPI\Model\CteSefazInfCteImp
     */
    public function getImp()
    {
        return $this->container['imp'];
    }

    /**
     * Sets imp
     *
     * @param \ACBrAPI\Model\CteSefazInfCteImp $imp imp
     *
     * @return self
     */
    public function setImp($imp)
    {
        if (is_null($imp)) {
            throw new \InvalidArgumentException('non-nullable imp cannot be null');
        }
        $this->container['imp'] = $imp;

        return $this;
    }

    /**
     * Gets inf_cte_norm
     *
     * @return \ACBrAPI\Model\CteSefazInfCTeNorm|null
     */
    public function getInfCteNorm()
    {
        return $this->container['inf_cte_norm'];
    }

    /**
     * Sets inf_cte_norm
     *
     * @param \ACBrAPI\Model\CteSefazInfCTeNorm|null $inf_cte_norm inf_cte_norm
     *
     * @return self
     */
    public function setInfCteNorm($inf_cte_norm)
    {
        if (is_null($inf_cte_norm)) {
            throw new \InvalidArgumentException('non-nullable inf_cte_norm cannot be null');
        }
        $this->container['inf_cte_norm'] = $inf_cte_norm;

        return $this;
    }

    /**
     * Gets inf_cte_comp
     *
     * @return \ACBrAPI\Model\CteSefazInfCteComp[]|null
     */
    public function getInfCteComp()
    {
        return $this->container['inf_cte_comp'];
    }

    /**
     * Sets inf_cte_comp
     *
     * @param \ACBrAPI\Model\CteSefazInfCteComp[]|null $inf_cte_comp inf_cte_comp
     *
     * @return self
     */
    public function setInfCteComp($inf_cte_comp)
    {
        if (is_null($inf_cte_comp)) {
            throw new \InvalidArgumentException('non-nullable inf_cte_comp cannot be null');
        }

        if ((count($inf_cte_comp) > 10)) {
            throw new \InvalidArgumentException('invalid value for $inf_cte_comp when calling CteSefazInfCte., number of items must be less than or equal to 10.');
        }
        $this->container['inf_cte_comp'] = $inf_cte_comp;

        return $this;
    }

    /**
     * Gets aut_xml
     *
     * @return \ACBrAPI\Model\CteSefazAutXML[]|null
     */
    public function getAutXml()
    {
        return $this->container['aut_xml'];
    }

    /**
     * Sets aut_xml
     *
     * @param \ACBrAPI\Model\CteSefazAutXML[]|null $aut_xml aut_xml
     *
     * @return self
     */
    public function setAutXml($aut_xml)
    {
        if (is_null($aut_xml)) {
            throw new \InvalidArgumentException('non-nullable aut_xml cannot be null');
        }

        if ((count($aut_xml) > 10)) {
            throw new \InvalidArgumentException('invalid value for $aut_xml when calling CteSefazInfCte., number of items must be less than or equal to 10.');
        }
        $this->container['aut_xml'] = $aut_xml;

        return $this;
    }

    /**
     * Gets inf_resp_tec
     *
     * @return \ACBrAPI\Model\CteSefazRespTec|null
     */
    public function getInfRespTec()
    {
        return $this->container['inf_resp_tec'];
    }

    /**
     * Sets inf_resp_tec
     *
     * @param \ACBrAPI\Model\CteSefazRespTec|null $inf_resp_tec inf_resp_tec
     *
     * @return self
     */
    public function setInfRespTec($inf_resp_tec)
    {
        if (is_null($inf_resp_tec)) {
            throw new \InvalidArgumentException('non-nullable inf_resp_tec cannot be null');
        }
        $this->container['inf_resp_tec'] = $inf_resp_tec;

        return $this;
    }

    /**
     * Gets inf_solic_nff
     *
     * @return \ACBrAPI\Model\CteSefazInfSolicNFF|null
     */
    public function getInfSolicNff()
    {
        return $this->container['inf_solic_nff'];
    }

    /**
     * Sets inf_solic_nff
     *
     * @param \ACBrAPI\Model\CteSefazInfSolicNFF|null $inf_solic_nff inf_solic_nff
     *
     * @return self
     */
    public function setInfSolicNff($inf_solic_nff)
    {
        if (is_null($inf_solic_nff)) {
            throw new \InvalidArgumentException('non-nullable inf_solic_nff cannot be null');
        }
        $this->container['inf_solic_nff'] = $inf_solic_nff;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


