<?php
/**
 * RTCInfoTributosAbrasfFed
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ACBrAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ACBr API
 *
 * API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ACBrAPI\Model;

use \ArrayAccess;
use \ACBrAPI\ObjectSerializer;

/**
 * RTCInfoTributosAbrasfFed Class Doc Comment
 *
 * @category Class
 * @description Grupo de informações relativas aos valores da CBS.
 * @package  ACBrAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RTCInfoTributosAbrasfFed implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RTCInfoTributosAbrasfFed';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'p_cbs' => 'float',
        'p_red_aliq_cbs' => 'float',
        'p_aliq_efet_cbs' => 'float',
        'v_cbs' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'p_cbs' => null,
        'p_red_aliq_cbs' => null,
        'p_aliq_efet_cbs' => null,
        'v_cbs' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'p_cbs' => true,
		'p_red_aliq_cbs' => true,
		'p_aliq_efet_cbs' => true,
		'v_cbs' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'p_cbs' => 'pCBS',
        'p_red_aliq_cbs' => 'pRedAliqCBS',
        'p_aliq_efet_cbs' => 'pAliqEfetCBS',
        'v_cbs' => 'vCBS'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'p_cbs' => 'setPCbs',
        'p_red_aliq_cbs' => 'setPRedAliqCbs',
        'p_aliq_efet_cbs' => 'setPAliqEfetCbs',
        'v_cbs' => 'setVCbs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'p_cbs' => 'getPCbs',
        'p_red_aliq_cbs' => 'getPRedAliqCbs',
        'p_aliq_efet_cbs' => 'getPAliqEfetCbs',
        'v_cbs' => 'getVCbs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('p_cbs', $data ?? [], null);
        $this->setIfExists('p_red_aliq_cbs', $data ?? [], null);
        $this->setIfExists('p_aliq_efet_cbs', $data ?? [], null);
        $this->setIfExists('v_cbs', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['p_cbs']) && ($this->container['p_cbs'] < 0)) {
            $invalidProperties[] = "invalid value for 'p_cbs', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['p_red_aliq_cbs']) && ($this->container['p_red_aliq_cbs'] < 0)) {
            $invalidProperties[] = "invalid value for 'p_red_aliq_cbs', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['p_aliq_efet_cbs']) && ($this->container['p_aliq_efet_cbs'] < 0)) {
            $invalidProperties[] = "invalid value for 'p_aliq_efet_cbs', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['v_cbs']) && ($this->container['v_cbs'] < 0)) {
            $invalidProperties[] = "invalid value for 'v_cbs', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets p_cbs
     *
     * @return float|null
     */
    public function getPCbs()
    {
        return $this->container['p_cbs'];
    }

    /**
     * Sets p_cbs
     *
     * @param float|null $p_cbs Alíquota da União para CBS.
     *
     * @return self
     */
    public function setPCbs($p_cbs)
    {
        if (is_null($p_cbs)) {
            array_push($this->openAPINullablesSetToNull, 'p_cbs');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('p_cbs', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($p_cbs) && ($p_cbs < 0)) {
            throw new \InvalidArgumentException('invalid value for $p_cbs when calling RTCInfoTributosAbrasfFed., must be bigger than or equal to 0.');
        }

        $this->container['p_cbs'] = $p_cbs;

        return $this;
    }

    /**
     * Gets p_red_aliq_cbs
     *
     * @return float|null
     */
    public function getPRedAliqCbs()
    {
        return $this->container['p_red_aliq_cbs'];
    }

    /**
     * Sets p_red_aliq_cbs
     *
     * @param float|null $p_red_aliq_cbs Percentual da redução de alíquota da CBS.
     *
     * @return self
     */
    public function setPRedAliqCbs($p_red_aliq_cbs)
    {
        if (is_null($p_red_aliq_cbs)) {
            array_push($this->openAPINullablesSetToNull, 'p_red_aliq_cbs');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('p_red_aliq_cbs', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($p_red_aliq_cbs) && ($p_red_aliq_cbs < 0)) {
            throw new \InvalidArgumentException('invalid value for $p_red_aliq_cbs when calling RTCInfoTributosAbrasfFed., must be bigger than or equal to 0.');
        }

        $this->container['p_red_aliq_cbs'] = $p_red_aliq_cbs;

        return $this;
    }

    /**
     * Gets p_aliq_efet_cbs
     *
     * @return float|null
     */
    public function getPAliqEfetCbs()
    {
        return $this->container['p_aliq_efet_cbs'];
    }

    /**
     * Sets p_aliq_efet_cbs
     *
     * @param float|null $p_aliq_efet_cbs Alíquota efetiva da CBS.  pAliqEfetCBS = pCBS x (1 - pRedAliqCBS) x (1 - pRedutor)
     *
     * @return self
     */
    public function setPAliqEfetCbs($p_aliq_efet_cbs)
    {
        if (is_null($p_aliq_efet_cbs)) {
            array_push($this->openAPINullablesSetToNull, 'p_aliq_efet_cbs');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('p_aliq_efet_cbs', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($p_aliq_efet_cbs) && ($p_aliq_efet_cbs < 0)) {
            throw new \InvalidArgumentException('invalid value for $p_aliq_efet_cbs when calling RTCInfoTributosAbrasfFed., must be bigger than or equal to 0.');
        }

        $this->container['p_aliq_efet_cbs'] = $p_aliq_efet_cbs;

        return $this;
    }

    /**
     * Gets v_cbs
     *
     * @return float|null
     */
    public function getVCbs()
    {
        return $this->container['v_cbs'];
    }

    /**
     * Sets v_cbs
     *
     * @param float|null $v_cbs Valor da CBS (R$).  vCBS = vBC x (pCBS ou pAliqEfetCBS)
     *
     * @return self
     */
    public function setVCbs($v_cbs)
    {
        if (is_null($v_cbs)) {
            array_push($this->openAPINullablesSetToNull, 'v_cbs');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('v_cbs', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($v_cbs) && ($v_cbs < 0)) {
            throw new \InvalidArgumentException('invalid value for $v_cbs when calling RTCInfoTributosAbrasfFed., must be bigger than or equal to 0.');
        }

        $this->container['v_cbs'] = $v_cbs;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


